### ISSUE TITLE
Character animation without rigging

### ISSUE THREAD

**Issue by elkhalafy** [diegomacario/Animation-Experiments#1]
How are you?

I found Idea for character animation without rigs or bones. This idea created by pixar studios called character articulation through profile curves or Curvenent
They have been released the paper about this idea.
So please if you able to do this As standalone Free application for Windows OS. It will be great

Look at the video and download the paper too

https://youtu.be/gUJ4RxMdVn8

Download the paper here :-

https://graphics.pixar.com/library/ProfileMover/paper.pdf

Please let me know, you will create it or not

Thank you

**Comment by diegomacario** [comment]
Hi @elkhalafy! Thanks for sharing that YouTube video and paper. I didn't know about that technique for animating characters without bones, it's very cool.

Unfortunately this is beyond my skillset right now and I'm super busy with work and other projects, so I can't look into this. I hope you find someone who can help you.

**Comment by elkhalafy** [comment]
Okay brother, never mind
But if you accepted it anytime or after thinking if you would like to create it, please let me know
Thank you
